name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Display Go version
        run: go version
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.12.5'
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./...

    

    